Revert "Bump minify from 7.1.0 to 7.2.1 in /npm"
This reverts commit 0066fc8a2b54b0265013b9b29b1cff662021c447.

It caused an error when building the CSS:

```
Error: fn should be a function!
    at check (/home/jenkins/workspace/R_Transfer_Front_End_Test_master/npm/node_modules/try-to-catch/lib/try-to-catch.js:15:15)
    at module.exports (/home/jenkins/workspace/R_Transfer_Front_End_Test_master/npm/node_modules/try-to-catch/lib/try-to-catch.js:4:5)
    at minify (/home/jenkins/workspace/R_Transfer_Front_End_Test_master/npm/node_modules/minify/bin/minify.js:58:43)
```

Which mean that the CSS didn't load on the TDR site.

We'll investigate the upgrade and retry it once we've fixed the build issue.