Downgrade the JDK from version 16 to 15
Version 15 is the latest stable version. 16 was a pre-release version,
and has started to cause errors on deployment:

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
```